version: '3.8'

services:
  web:
    build: .
    
    command: daphne -b 0.0.0.0 -p 8000 gestion_docentes.gestion_docentes.asgi:application
    volumes:
      - .:/app
      - static_volume:/app/gestion_docentes/staticfiles
      - media_volume:/app/gestion_docentes/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:7-alpine

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/gestion_docentes/staticfiles
      - media_volume:/app/gestion_docentes/media
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
