"""
Django settings for gestion_docentes project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from django.urls import reverse_lazy
from django.templatetags.static import static
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# Key for encrypting IDs
ID_ENCRYPTION_KEY = os.environ.get('ID_ENCRYPTION_KEY', '').encode()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 't')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')
# ... cerca de ALLOWED_HOSTS ...

CSRF_TRUSTED_ORIGINS = ['https://aquienpasco.lat', 'https://www.aquienpasco.lat']

# Settings for running behind a reverse proxy like Nginx
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'unfold',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core',
    'tailwind',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestion_docentes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.unread_notifications_context',
                'core.context_processors.site_configuration_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_docentes.wsgi.application'
ASGI_APPLICATION = 'gestion_docentes.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.environ.get('REDIS_HOST'), os.environ.get('REDIS_PORT'))],
        },
    },
}

# If in DEBUG mode, override channel layer to use in-memory for local development
# This avoids needing a Redis server running locally.
if DEBUG:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST'),
        'PORT': os.environ.get('POSTGRES_PORT'),
    }
}

# Use in-memory SQLite database and an in-memory channel layer for tests
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

UNFOLD = {
    "SITE_HEADER": "Gestión de Docentes",
    "DASHBOARD_CALLBACK": "core.dashboard.dashboard_callback",
    "STYLES": [
        "https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css",
        "https://cdn.jsdelivr.net/npm/flatpickr/dist/themes/dark.css",
        lambda request: static("css/admin_custom.css"),
    ],
    "SCRIPTS": [
        "https://cdn.jsdelivr.net/npm/flatpickr",
        "https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/es.js",
        lambda request: static("js/admin_custom.js"),
    ],
    "SIDEBAR": {
        "show_search": False,
        "navigation": [
            {
                "title": "Principal",
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": "Gestión Académica",
                "icon": "school",
                "items": [
                    {
                        "title": "Semestres",
                        "icon": "date_range",
                        "link": reverse_lazy("admin:core_semestre_changelist"),
                    },
                    {
                        "title": "Carreras",
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:core_carrera_changelist"),
                    },
                    {
                        "title": "Especialidades",
                        "icon": "category",
                        "link": reverse_lazy("admin:core_especialidad_changelist"),
                    },
                    {
                        "title": "Cursos",
                        "icon": "book",
                        "link": reverse_lazy("admin:core_curso_changelist"),
                    },
                    {
                        "title": "Franjas Horarias",
                        "icon": "schedule",
                        "link": reverse_lazy("admin:core_franjahoraria_changelist"),
                    },
                    {
                        "title": "Días Especiales",
                        "icon": "event",
                        "link": reverse_lazy("admin:core_diaespecial_changelist"),
                    },
                ],
            },
            {
                "title": "Gestión de Inventario",
                "icon": "inventory_2",
                "items": [
                    {
                        "title": "Tipos de Activo",
                        "icon": "category",
                        "link": reverse_lazy("admin:core_tipoactivo_changelist"),
                    },
                    {
                        "title": "Activos",
                        "icon": "inventory",
                        "link": reverse_lazy("admin:core_activo_changelist"),
                    },
                    {
                        "title": "Reservas y Préstamos",
                        "icon": "event_available",
                        "link": reverse_lazy("admin:core_reserva_changelist"),
                    },
                ],
            },
            {
                "title": "Personal",
                "icon": "group",
                "items": [
                    {
                        "title": "Docentes",
                        "icon": "person",
                        "link": reverse_lazy("admin:core_personaldocente_changelist"),
                    },
                    {
                        "title": "Administradores",
                        "icon": "shield_person",
                        "link": reverse_lazy("admin:core_administrador_changelist"),
                    },
                    {
                        "title": "Grupos",
                        "icon": "groups",
                        "link": reverse_lazy("admin:core_grupo_changelist"),
                    },
                ],
            },
            {
                "title": "Documentos y Justificaciones",
                "icon": "folder_managed",
                "items": [
                    {
                        "title": "Documentos",
                        "icon": "folder",
                        "link": reverse_lazy("admin:core_documento_changelist"),
                        "badge": "core.badge_callbacks.documentos_badge_callback",
                    },
                    {
                        "title": "Tipos de Documento",
                        "icon": "description",
                        "link": reverse_lazy("admin:core_tipodocumento_changelist"),
                    },
                    {
                        "title": "Justificaciones",
                        "icon": "assignment_turned_in",
                        "link": reverse_lazy("admin:core_justificacion_changelist"),
                        "badge": "core.badge_callbacks.justificaciones_badge_callback",
                    },
                    {
                        "title": "Tipos de Justificación",
                        "icon": "rule",
                        "link": reverse_lazy("admin:core_tipojustificacion_changelist"),
                    },
                ],
            },
            {
                "title": "Asistencia",
                "icon": "event_available",
                "items": [
                    {
                        "title": "Registros de Asistencia",
                        "icon": "person_check",
                        "link": reverse_lazy("admin:core_asistencia_changelist"),
                    },
                    {
                        "title": "Asistencia Diaria",
                        "icon": "today",
                        "link": reverse_lazy("admin:core_asistenciadiaria_changelist"),
                    },
                    {
                        "title": "Solicitudes de Intercambio",
                        "icon": "swap_horiz",
                        "link": reverse_lazy("admin:core_solicitudintercambio_changelist"),
                        "badge": "core.badge_callbacks.solicitudes_intercambio_badge_callback",
                    },
                ],
            },
            {
                "title": "Comunicación",
                "icon": "campaign",
                "items": [
                    {
                        "title": "Anuncios",
                        "icon": "campaign",
                        "link": reverse_lazy("admin:core_anuncio_changelist"),
                    },
                    {
                        "title": "Notificaciones",
                        "icon": "notifications",
                        "link": reverse_lazy("admin:core_notificacion_changelist"),
                        "badge": "core.badge_callbacks.notificaciones_badge_callback",
                    },
                ],
            },
            {
                "title": "Configuración",
                "icon": "settings",
                "items": [
                    {
                        "title": "Configuración de la Institución",
                        "icon": "settings_applications",
                        "link": reverse_lazy("admin:core_configuracioninstitucion_changelist"),
                    },
                ],
            },
        ],
    },
}


AUTH_USER_MODEL = 'core.Docente'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

X_FRAME_OPTIONS = 'SAMEORIGIN'
