"""
Django settings for gestion_docentes project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=w1huy-2d3)$32m)$+8+*kkuz(+#hx)eio37q8(+94@o-+av&s'

# Key for encrypting IDs
ID_ENCRYPTION_KEY = b'J5YSFVZTupEKrBGPkvBODOR_B_uHBx2GZeKcO32JeUI='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'tailwind',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestion_docentes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.unread_notifications_context',
                'core.context_processors.site_configuration_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_docentes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.Docente'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

X_FRAME_OPTIONS = 'SAMEORIGIN'




JAZZMIN_SETTINGS = {
    # General settings
    "site_title": "Panel de Control",
    "site_header": "Gestión Docente",
    "site_brand": "SIGEDO",
    "welcome_sign": "Bienvenido al Panel de Control de SIGEDO",
    "copyright": "SIGEDO",
    "dashboard_url": "admin_dashboard",

    # Theme settings
    "theme": "litera",
    "dark_mode_theme": "darkly",

    # UI Tweaks
    "ui_tweaks": {
        "navbar_small_text": False,
        "footer_small_text": False,
        "body_small_text": False,
        "brand_small_text": False,
        "brand_colour": "navbar-primary",
        "accent": "accent-primary",
        "navbar": "navbar-dark",
        "no_navbar_border": False,
        "sidebar": "sidebar-dark-primary",
        "sidebar_nav_flat_style": True,
        "sidebar_nav_child_indent": False,
        "sidebar_nav_compact_style": True,
    },

    # Menu settings
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["core"], # App order

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core.personaldocente": "fas fa-chalkboard-teacher",
        "core.administrador": "fas fa-user-shield",
        "core.carrera": "fas fa-university",
        "core.especialidad": "fas fa-atom",
        "core.semestre": "fas fa-calendar-alt",
        "core.curso": "fas fa-book-reader",
        "core.grupo": "fas fa-layer-group",
        "core.franjahoraria": "fas fa-clock",
        "core.asistencia": "fas fa-check-circle",
        "core.asistenciadiaria": "fas fa-calendar-check",
        "core.justificacion": "fas fa-file-medical-alt",
        "core.tipojustificacion": "fas fa-tags",
        "core.documento": "fas fa-file-alt",
        "core.versiondocumento": "fas fa-file-upload",
        "core.tipodocumento": "fas fa-tag",
        "core.anuncio": "fas fa-bullhorn",
        "core.notificacion": "fas fa-bell",
        "core.solicitudintercambio": "fas fa-exchange-alt",
        "core.diaespecial": "fas fa-calendar-star",
        "core.configuracioninstitucion": "fas fa-cogs",
    },

    "custom_links": {
        "core": [
            {
                "name": "Planificador de Horarios",
                "url": "planificador_horarios",
                "icon": "fas fa-calendar-alt",
                "permissions": ["core.view_curso"]
            },
            {
                "name": "Reporte de Asistencia",
                "url": "reporte_asistencia",
                "icon": "fas fa-chart-bar",
                "permissions": ["core.view_asistencia"]
            },
            {
                "name": "Generador de Credenciales",
                "url": "lista_credenciales",
                "icon": "fas fa-id-card",
                "permissions": ["core.view_docente"]
            }
        ]
    },

    "related_modal_active": True,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "litera",
    "dark_mode_theme": "darkly",
}