# Generated by Django 5.2.4 on 2025-08-03 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninstitucion',
            name='facultad',
            field=models.ForeignKey(blank=True, help_text='Seleccione la facultad o carrera principal para la cual se está configurando el sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carrera'),
        ),
    ]
