# Generated by Django 5.2.4 on 2025-08-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_anuncio"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioninstitucion",
            name="tiempo_limite_tardanza",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Minutos de tolerancia para considerar una asistencia como tardanza.",
            ),
        ),
    ]
