# Generated by Django 5.2.4 on 2025-08-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tipojustificacion_justificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asistencia",
            options={
                "permissions": [("view_reporte", "Puede ver reportes de asistencia")]
            },
        ),
        migrations.AlterModelOptions(
            name="curso",
            options={
                "permissions": [
                    ("view_planificador", "Puede ver el planificador de horarios")
                ]
            },
        ),
    ]
