# Generated by Django 5.2.4 on 2025-08-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_create_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="dni",
            field=models.CharField(
                blank=True, db_index=True, max_length=8, null=True, unique=True
            ),
        ),
    ]
