# Generated by Django 5.2.4 on 2025-08-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_create_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioninstitucion",
            name="nombre_dashboard",
            field=models.CharField(
                default="Gestión Docente",
                help_text="El nombre que se mostrará en el dashboard.",
                max_length=100,
            ),
        ),
    ]
