# Generated by Django 5.2.4 on 2025-08-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_configuracioninstitucion_nombre_dashboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="docente",
            name="rfid_uid",
            field=models.CharField(
                blank=True,
                help_text="UID de la tarjeta RFID asignada al docente",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
