# Generated by Django 5.2.4 on 2025-08-10 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_docente_rfid_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asistenciadiaria",
            name="fecha",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="asistenciadiaria",
            name="foto_verificacion",
            field=models.ImageField(
                blank=True, null=True, upload_to="verificacion_diaria/%Y/%m/%d/"
            ),
        ),
    ]
