# Generated by Django 5.2.4 on 2025-08-10 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_asistenciadiaria_fecha_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoActivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Laptop, Proyector, Monitor",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Activo",
                "verbose_name_plural": "Tipos de Activos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Activo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "codigo_patrimonial",
                    models.CharField(
                        help_text="Código único patrimonial o número de serie",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("ASIGNADO", "Asignado"),
                            ("EN_MANTENIMIENTO", "En Mantenimiento"),
                            ("DE_BAJA", "De Baja"),
                        ],
                        default="DISPONIBLE",
                        max_length=20,
                    ),
                ),
                ("fecha_adquisicion", models.DateField(blank=True, null=True)),
                ("fecha_asignacion", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activos",
                        to="core.tipoactivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activo",
                "verbose_name_plural": "Activos",
                "ordering": ["nombre"],
            },
        ),
    ]
