# Generated by Django 5.2.4 on 2025-08-10 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_tipoactivo_activo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_reserva", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("RESERVADO", "Reservado"),
                            ("EN_USO", "En Uso"),
                            ("FINALIZADO", "Finalizado"),
                            ("CANCELADO", "Cancelado por usuario"),
                            ("EXPIRADO", "Expirado automáticamente"),
                        ],
                        default="RESERVADO",
                        max_length=30,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "fecha_confirmacion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que se recoge el equipo.",
                        null=True,
                    ),
                ),
                (
                    "fecha_finalizacion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que se devuelve el equipo.",
                        null=True,
                    ),
                ),
                (
                    "activo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="core.activo",
                    ),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "franja_horaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="core.franjahoraria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva de Activo",
                "verbose_name_plural": "Reservas de Activos",
                "ordering": ["-fecha_reserva", "-franja_horaria__hora_inicio"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("estado__in", ["RESERVADO", "EN_USO"])),
                        fields=("activo", "fecha_reserva", "franja_horaria"),
                        name="unique_reserva_activa",
                    )
                ],
            },
        ),
    ]
