# Generated by Django 5.2.4 on 2025-08-21 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_reserva"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reserva",
            options={
                "ordering": ["-fecha_reserva", "-franja_horaria_inicio__hora_inicio"],
                "verbose_name": "Reserva de Activo",
                "verbose_name_plural": "Reservas de Activos",
            },
        ),
        migrations.RemoveConstraint(
            model_name="reserva",
            name="unique_reserva_activa",
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='franja_horaria',
            new_name='franja_horaria_inicio',
        ),
        migrations.AddField(
            model_name="reserva",
            name="franja_horaria_fin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservas_fin",
                to="core.franjahoraria",
            ),
        ),
    ]
