# Generated by Django 5.2.4 on 2025-08-21 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_reserva_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="franja_horaria_inicio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservas_inicio",
                to="core.franjahoraria",
            ),
        ),
    ]
