# Generated by Django 5.2.4 on 2025-08-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_reserva_franja_horaria_inicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="dia_semana",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Día de la semana como número (0=Lunes, 1=Martes...)",
                null=True,
            ),
        ),
    ]
