# Generated by Django 5.2.4 on 2025-08-21 20:33

from django.db import migrations

def populate_dia_semana(apps, schema_editor):
    """
    Populates the new 'dia_semana' field based on the existing 'dia' field.
    """
    Curso = apps.get_model('core', 'Curso')
    DIAS = {'Lunes': 0, 'Martes': 1, 'Miércoles': 2, 'Jueves': 3, 'Viernes': 4}

    # We iterate through all courses and update them one by one.
    # For a very large dataset, using .iterator() would be more memory-efficient.
    for curso in Curso.objects.all():
        if curso.dia:
            curso.dia_semana = DIAS.get(curso.dia)
            # We use update_fields to only touch the 'dia_semana' field and avoid
            # triggering other side-effects of the model's save() method.
            curso.save(update_fields=['dia_semana'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_curso_dia_semana'),
    ]

    operations = [
        migrations.RunPython(populate_dia_semana, migrations.RunPython.noop),
    ]
