# Generated by Django 5.2.4 on 2025-08-24 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_populate_dia_semana"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="curso",
            field=models.ForeignKey(
                blank=True,
                help_text="Curso asociado a la reserva (opcional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservas_equipos",
                to="core.curso",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="franja_horaria_inicio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservas_inicio",
                to="core.franjahoraria",
            ),
        ),
    ]
