# Generated by Django 5.0 on 2025-08-30 17:57

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_link_reserva_to_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='horas_academicas_semanales',
            field=models.PositiveIntegerField(default=2, help_text='Número total de bloques de 50 minutos que el curso requiere a la semana.'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='dia',
            field=models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], help_text='DEPRECADO: Usar BloqueHorario', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='dia_semana',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, editable=False, help_text='DEPRECADO: Usar BloqueHorario', null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion_bloques',
            field=models.IntegerField(default=2, help_text='DEPRECADO: Representa la carga horaria semanal. Usar horas_academicas_semanales.'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='horario_fin',
            field=models.TimeField(blank=True, help_text='DEPRECADO: Usar BloqueHorario', null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='horario_inicio',
            field=models.TimeField(blank=True, help_text='DEPRECADO: Usar BloqueHorario', null=True),
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=20)),
                ('duracion_bloques', models.PositiveIntegerField(default=1, help_text='Duración de este bloque específico en unidades de 50 minutos.')),
                ('horario_inicio', models.TimeField(editable=False)),
                ('horario_fin', models.TimeField(editable=False)),
                ('dia_semana', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horario', to='core.curso')),
                ('franja_inicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloques_inicio', to='core.franjahoraria')),
            ],
            options={
                'verbose_name': 'Bloque de Horario',
                'verbose_name_plural': 'Bloques de Horario',
                'ordering': ['dia_semana', 'horario_inicio'],
                'unique_together': {('curso', 'dia', 'franja_inicio')},
            },
        ),
    ]
