# Generated by Django 5.2.4 on 2025-08-28 06:00
# Manually crafted by Jules for data migration

from django.db import migrations, models
import django.db.models.deletion

def migrar_datos_horario(apps, schema_editor):
    """
    Migrates data from old schedule fields in Curso to the new BloqueCurso model.
    Also, it copies the value from the old 'duracion_bloques' to 'horas_semanales'.
    This function is designed to be safe and check for attribute existence.
    """
    Curso = apps.get_model('core', 'Curso')
    BloqueCurso = apps.get_model('core', 'BloqueCurso')
    db_alias = schema_editor.connection.alias

    for curso in Curso.objects.using(db_alias).all():
        # Step 1: Copy the duration value to the new 'horas_semanales' field for all courses.
        # This assumes the old 'duracion_bloques' represented the total weekly hours.
        if hasattr(curso, 'duracion_bloques') and curso.duracion_bloques is not None:
            curso.horas_semanales = curso.duracion_bloques
            curso.save(update_fields=['horas_semanales'])

        # Step 2: Create a BloqueCurso instance only for courses that had a schedule assigned.
        if (hasattr(curso, 'dia') and curso.dia and
            hasattr(curso, 'horario_inicio') and curso.horario_inicio and
            hasattr(curso, 'horario_fin') and curso.horario_fin and
            hasattr(curso, 'duracion_bloques') and curso.duracion_bloques):

            BloqueCurso.objects.using(db_alias).create(
                curso=curso,
                dia=curso.dia,
                hora_inicio=curso.horario_inicio,
                hora_fin=curso.horario_fin,
                duracion_bloques=curso.duracion_bloques
            )

def revertir_migracion(apps, schema_editor):
    """
    Reverts the data migration. This is a placeholder and would need
    complex logic to be fully implemented, but it's good practice to have it.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_link_reserva_to_curso'),
    ]

    operations = [
        # Temporarily add the old fields to the new BloqueCurso model definition
        # so that the data migration function can access them.
        # This is a bit of a hack, but it's a common pattern for complex migrations.

        # 1. Create the new model
        migrations.CreateModel(
            name='BloqueCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_bloques', models.IntegerField(help_text='Número de bloques de 50 minutos que dura este bloque específico.')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='core.curso')),
            ],
            options={
                'verbose_name': 'Bloque de Curso',
                'verbose_name_plural': 'Bloques de Curso',
                'ordering': ['dia', 'hora_inicio'],
            },
        ),

        # 2. Add the new field to Curso, keeping the old ones for now
        migrations.AddField(
            model_name='curso',
            name='horas_semanales',
            field=models.IntegerField(default=2, help_text='Número total de horas pedagógicas (bloques de 50 min) que el curso requiere a la semana.'),
        ),

        # 3. Run the data migration script
        migrations.RunPython(migrar_datos_horario, reverse_code=revertir_migracion),

        # 4. Now that data is migrated, remove the old fields
        migrations.RemoveField(
            model_name='curso',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='horario_fin',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='horario_inicio',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='duracion_bloques',
        ),
    ]
