# Generated by Django 5.2.4 on 2025-08-27 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_link_reserva_to_curso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="tipo_curso",
            field=models.CharField(
                choices=[("ESPECIALIDAD", "Especialidad"), ("GENERAL", "General")],
                default="ESPECIALIDAD",
                help_text="Indica si el curso es de especialidad o de estudios generales.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="docente",
            name="disponibilidad",
            field=models.CharField(
                choices=[
                    ("COMPLETO", "Tiempo Completo (Mañana y Tarde)"),
                    ("MANANA", "Solo Mañana"),
                    ("TARDE", "Solo Tarde"),
                ],
                default="COMPLETO",
                help_text="Define la disponibilidad del docente para la asignación de horarios.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="observaciones",
            field=models.TextField(
                blank=True,
                help_text="Notas internas para la administración. No son visibles para el docente.",
            ),
        ),
        migrations.AlterField(
            model_name="justificacion",
            name="observaciones_revision",
            field=models.TextField(
                blank=True,
                help_text="Notas internas del administrador que revisa la solicitud. Visibles solo para otros administradores.",
            ),
        ),
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_group_chat",
                    models.BooleanField(default=False, verbose_name="Es Grupal"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del grupo de chat",
                        max_length=255,
                        null=True,
                        verbose_name="Nombre del Grupo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Participantes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversación de Chat",
                "verbose_name_plural": "Conversaciones de Chat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y Hora"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.chatconversation",
                        verbose_name="Conversación",
                    ),
                ),
                (
                    "read_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="read_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Leído por",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Remitente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Chat",
                "verbose_name_plural": "Mensajes de Chat",
                "ordering": ["timestamp"],
            },
        ),
    ]
