# Generated by Django 5.0 on 2025-08-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_bloquehorario_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='duracion_bloques',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='horario_fin',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='horario_inicio',
        ),
    ]
