# Generated by Django 5.2.4 on 2025-08-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_deprecated_curso_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='excepcion_horario',
            field=models.BooleanField(default=False, help_text='Permite que este curso se asigne en la tarde aunque sea de un semestre bajo.'),
        ),
    ]
