# Generated by Django 5.2.4 on 2025-09-02 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_curso_excepcion_horario"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="tolerancia_tardanza_minutos",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tolerancia de tardanza en minutos, específica para este curso. Si se deja en blanco, se usará la configuración general de la institución.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="docente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cursos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="tipo_curso",
            field=models.CharField(
                choices=[("ESPECIALIDAD", "Especialidad"), ("GENERAL", "General")],
                default="ESPECIALIDAD",
                help_text="Indica si el curso es de especialidad o de estudios generales.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="docente",
            name="disponibilidad",
            field=models.CharField(
                choices=[
                    ("COMPLETO", "Tiempo Completo (Mañana y Tarde)"),
                    ("MANANA", "Solo Mañana"),
                    ("TARDE", "Solo Tarde"),
                ],
                default="COMPLETO",
                help_text="Define la disponibilidad del docente para la asignación de horarios.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="observaciones",
            field=models.TextField(
                blank=True,
                help_text="Notas internas para la administración. No son visibles para el docente.",
            ),
        ),
        migrations.AlterField(
            model_name="justificacion",
            name="observaciones_revision",
            field=models.TextField(
                blank=True,
                help_text="Notas internas del administrador que revisa la solicitud. Visibles solo para otros administradores.",
            ),
        ),
    ]
