# Generated by Django 5.2.4 on 2025-12-24 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_add_tolerancia_tardanza_to_curso"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("ubicacion", models.CharField(blank=True, max_length=200, null=True)),
                ("es_laboratorio", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="bloquehorario",
            name="aula",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bloques_horario",
                to="core.aula",
            ),
        ),
        migrations.CreateModel(
            name="BloqueNoLectivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("Lunes", "Lunes"),
                            ("Martes", "Martes"),
                            ("Miércoles", "Miércoles"),
                            ("Jueves", "Jueves"),
                            ("Viernes", "Viernes"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duracion_bloques", models.PositiveIntegerField(default=1)),
                ("motivo", models.CharField(max_length=255)),
                ("horario_inicio", models.TimeField(editable=False)),
                ("horario_fin", models.TimeField(editable=False)),
                (
                    "dia_semana",
                    models.PositiveSmallIntegerField(db_index=True, editable=False),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloques_no_lectivos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "franja_inicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bloques_no_lectivos",
                        to="core.franjahoraria",
                    ),
                ),
            ],
        ),
    ]
