# Generated by Django 5.2.4 on 2025-12-24 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_add_tolerancia_tardanza_to_curso"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloqueNoLectivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("Lunes", "Lunes"),
                            ("Martes", "Martes"),
                            ("Miércoles", "Miércoles"),
                            ("Jueves", "Jueves"),
                            ("Viernes", "Viernes"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "duracion_bloques",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Duración de este bloque en unidades de 50 minutos.",
                    ),
                ),
                (
                    "motivo",
                    models.TextField(
                        help_text="Razón de la indisponibilidad (ej. Gestión, Investigación)"
                    ),
                ),
                ("horario_inicio", models.TimeField(editable=False)),
                ("horario_fin", models.TimeField(editable=False)),
                (
                    "dia_semana",
                    models.PositiveSmallIntegerField(db_index=True, editable=False),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloques_no_lectivos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "franja_inicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bloques_gestion_inicio",
                        to="core.franjahoraria",
                    ),
                ),
                (
                    "semestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloques_no_lectivos",
                        to="core.semestre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloque No Lectivo (Gestión)",
                "verbose_name_plural": "Bloques No Lectivos",
                "ordering": ["dia_semana", "horario_inicio"],
            },
        ),
    ]
