# Generated by Django 5.2.4 on 2025-12-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_aula_bloquehorario_aula_bloquenolectivo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="especialidad",
        ),
        migrations.AddField(
            model_name="curso",
            name="especialidades",
            field=models.ManyToManyField(
                blank=True, related_name="cursos", to="core.especialidad"
            ),
        ),
    ]
