# Generated by Django 5.2.4 on 2025-12-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_remove_curso_especialidad_curso_especialidades"),
    ]

    operations = [
        migrations.AddField(
            model_name="asistenciadiaria",
            name="foto_salida",
            field=models.ImageField(
                blank=True, null=True, upload_to="verificacion_diaria/salidas/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="asistenciadiaria",
            name="hora_salida",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
