# Generated by Django 5.2.4 on 2025-12-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_asistenciadiaria_foto_salida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Token de notificaciones Push (Firebase)', max_length=255, null=True),
        ),
    ]
