# Generated by Django 5.2.4 on 2025-12-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_docente_fcm_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacion",
            name="mensaje",
            field=models.TextField(),
        ),
    ]
