# Generated by Django 5.2.4 on 2025-12-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_historicalasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninstitucion',
            name='validar_geolocalizacion',
            field=models.BooleanField(default=True, help_text='Si está activo, se validará que el docente esté dentro del campus para marcar.'),
        ),
    ]
