# Generated by Django 5.2.4 on 2025-12-31 03:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_configuracioninstitucion_validar_geolocalizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdelantoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('motivo', models.TextField(help_text='Motivo por el cual se adelanta la clase.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('docente', 'curso', 'fecha')},
            },
        ),
    ]
