# Generated by Django 5.2.4 on 2026-01-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_adelantoclase"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioninstitucion",
            name="hora_fin_asistencia_general",
            field=models.TimeField(
                default="23:00",
                help_text="Hora hasta la cual se permite marcar la Entrada General.",
            ),
        ),
        migrations.AddField(
            model_name="configuracioninstitucion",
            name="hora_inicio_asistencia_general",
            field=models.TimeField(
                default="07:00",
                help_text="Hora desde la cual se permite marcar la Entrada General.",
            ),
        ),
    ]
