# Generated by Django 5.2.4 on 2026-01-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_configuracioninstitucion_hora_fin_asistencia_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='observacion_salida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalasistencia',
            name='observacion_salida',
            field=models.TextField(blank=True, null=True),
        ),
    ]
