# Generated by Django 5.2.4 on 2026-01-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_asistencia_observacion_salida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='celular',
            field=models.CharField(blank=True, help_text='Número de celular del docente', max_length=20, null=True),
        ),
    ]
