# Generated by Django 5.2.4 on 2026-01-03 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_docente_celular"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="adelantoclase",
            unique_together=set(),
        ),
        migrations.CreateModel(
            name="RecuperacionClase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_a_recuperar",
                    models.DateField(
                        help_text="Fecha de la clase que no se dictó o se dictará en otro momento"
                    ),
                ),
                (
                    "fecha_propuesta",
                    models.DateTimeField(
                        help_text="Fecha y hora propuesta para la recuperación"
                    ),
                ),
                (
                    "duracion_minutos",
                    models.IntegerField(default=90, help_text="Duración en minutos"),
                ),
                ("motivo", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, help_text="Observaciones del administrador"
                    ),
                ),
                (
                    "aula_solicitada",
                    models.ForeignKey(
                        blank=True,
                        help_text="Aula sugerida (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.aula",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.curso"
                    ),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
