# Generated by Django 5.2.4 on 2026-01-23 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_adelantoclase_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asistencia",
            name="observacion_salida",
        ),
        migrations.RemoveField(
            model_name="historicalasistencia",
            name="observacion_salida",
        ),
        migrations.AddField(
            model_name="asistencia",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PRESENTE", "Presente"),
                    ("TARDANZA", "Tardanza"),
                    ("JUSTIFICADO", "Justificado"),
                    ("FALTA", "Falta"),
                ],
                default="PRESENTE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="justificacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asistencias_vinculadas",
                to="core.justificacion",
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="latitud_entrada",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="latitud_salida",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="longitud_entrada",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="longitud_salida",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalasistencia",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PRESENTE", "Presente"),
                    ("TARDANZA", "Tardanza"),
                    ("JUSTIFICADO", "Justificado"),
                    ("FALTA", "Falta"),
                ],
                default="PRESENTE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalasistencia",
            name="justificacion",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.justificacion",
            ),
        ),
        migrations.AddField(
            model_name="historicalasistencia",
            name="latitud_entrada",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalasistencia",
            name="latitud_salida",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalasistencia",
            name="longitud_entrada",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalasistencia",
            name="longitud_salida",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
